--- 
rubyforge_project: treequel
project_requirements: {}

project_pubdir: /usr/local/www/public/code
project_description: |-
  A Sequel-like DSL library for interacting with hierarchical datasets. It's mostly experimental
  still.
rubyforge_group: deveiate
author_name: Michael Granger
project_pubhost: deveiate
project_homepage: http://deveiate.org/projects/Treequel
project_dependencies: 
  redleaf: ">=0"
project_summary: A Sequel-like DSL library for interacting with hierarchical datasets
project_name: Treequel
version_file: treequel.rb
additional_pkgfiles: []

dev_dependencies: 
  ldap: ">=0"
author_email: ged@FaerieMUD.org
post_install_message: ""
