--- 
project_name: Treequel
project_homepage: http://deveiate.org/projects/Treequel
project_summary: An honest LDAP library
project_description: |-
  A library for interacting with LDAP (modeled after Sequel). It is an attempt to remove
  the impedence mismatch of trying to treat LDAP as if it's a relational database, and
  instead embrace its hierarchical, free-form nature.
project_pubhost: deveiate
project_pubdir: /usr/local/www/public/code
gem_pubhost: rubygems.org
release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
release_smtphost: mail.faeriemud.org
post_install_message: |-
  If you want to use the included 'treequel' LDAP shell, you'll need to install
  the following libraries as well:
      - termios
      - ruby-terminfo
      - columnize
      - diff-lcs
authors: 
  Mahlon E. Smith: mahlon@martini.nu
  Michael Granger: ged@FaerieMUD.org
project_dependencies: 
  ruby-ldap: ">= 0.9.9"
dev_dependencies: 
  columnize: ">= 0.3.1"
  ruby-termios: ">= 0.9.6"
  diff-lcs: ">= 1.1.2"
  ruby-terminfo: ">= 0.1.1"
  rspec: ">= 2.0.1"
project_requirements: 
  ldap: ">=0"
additional_pkgfiles: 
- examples/**/*.{rb,erb,css,png}
excluded_pkgfiles: []

required_ruby_version: ">=1.8.7"
version_file: treequel.rb
